apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
        - name: trivy
          image: aquasec/trivy:latest
          command: ["trivy", "server"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trivy
  namespace: security
spec:
  selector:
    app: trivy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
