apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-shop
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-shop
  template:
    metadata:
      labels:
        app: web-shop
    spec:
      containers:
        - name: web-shop
          image: dulcinee/web-shop
          ports:
            - containerPort: 80
      imagePullSecrets:          
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-shop-service
  namespace: webapp
spec:
  selector:
    app: web-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32675
  type: NodePort
